#!/usr/bin/env node
// Builds the extension for one or more browsers. No dependencies.
//
//   node scripts/build.mjs safari|chrome|firefox|all [--dev]
//
// Output goes to dist/<browser>/. --dev also runs the content script on
// http://localhost so test/mock-player.html can be used.
//
// The base manifest is MV3. A platform override with "manifest_version": 2 is
// converted to MV2 (browser_action, persistent background page, etc.).
import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const BROWSERS = ['safari', 'chrome', 'firefox'];

// Each bundle = lib/common.js + entry, wrapped in an IIFE so nothing leaks
// into the page (content script) or collides on re-injection.
const BUNDLES = {
  'background.js': ['lib/common.js', 'background.js'],
  'content.js': ['lib/common.js', 'content.js'],
  'popup/popup.js': ['lib/common.js', 'popup/popup.js'],
};
const COPY = ['icons', 'popup/popup.html', 'popup/popup.css'];
const DEV_MATCHES = ['http://localhost/*', 'http://127.0.0.1/*'];

const readJSON = (p) => JSON.parse(readFileSync(p, 'utf8'));

function merge(base, over) {
  const out = { ...base };
  for (const [k, v] of Object.entries(over)) {
    if (k === '//') continue;
    out[k] = v && typeof v === 'object' && !Array.isArray(v) && base[k] && typeof base[k] === 'object'
      ? merge(base[k], v)
      : v;
  }
  return out;
}

function toMV2(m) {
  const out = { ...m, manifest_version: 2 };
  if (out.action) {
    out.browser_action = out.action;
    delete out.action;
  }
  if (out.host_permissions) {
    out.permissions = [...(out.permissions || []), ...out.host_permissions];
    delete out.host_permissions;
  }
  if (out.optional_host_permissions) {
    out.optional_permissions = [...(out.optional_permissions || []), ...out.optional_host_permissions];
    delete out.optional_host_permissions;
  }
  if (out.background?.service_worker) {
    out.background = { scripts: [out.background.service_worker], persistent: true };
  }
  return out;
}

function buildManifest(browser, dev) {
  let m = merge(readJSON(join(src, 'manifest.base.json')), readJSON(join(root, 'platforms', `${browser}.json`)));
  if (dev) {
    m.content_scripts = m.content_scripts.map((cs) => ({ ...cs, matches: [...cs.matches, ...DEV_MATCHES] }));
    m.host_permissions = [...(m.host_permissions || []), ...DEV_MATCHES];
    m.name += ' (dev)';
  }
  if (m.manifest_version === 2) m = toMV2(m);
  return m;
}

function bundle(files, browser) {
  const parts = files.map((f) => `// ---- ${f} ----\n${readFileSync(join(src, f), 'utf8')}`);
  return `// Deep Discipleship Remote (${browser}) — generated by scripts/build.mjs, do not edit.\n` +
    `(() => {\n'use strict';\n${parts.join('\n')}\n})();\n`;
}

function build(browser, dev) {
  const out = join(root, 'dist', browser);
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });

  const manifest = buildManifest(browser, dev);
  writeFileSync(join(out, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

  for (const [dest, files] of Object.entries(BUNDLES)) {
    mkdirSync(dirname(join(out, dest)), { recursive: true });
    writeFileSync(join(out, dest), bundle(files, browser));
  }
  for (const p of COPY) {
    cpSync(join(src, p), join(out, p), { recursive: true });
  }
  const icons = readdirSync(join(out, 'icons'));
  if (!icons.length) throw new Error('no icons; run node tools/gen-icons.mjs');
  console.log(`built dist/${browser} (MV${manifest.manifest_version}${dev ? ', dev' : ''})`);
}

const args = process.argv.slice(2);
const dev = args.includes('--dev');
const target = args.find((a) => !a.startsWith('--')) || 'all';
const targets = target === 'all' ? BROWSERS : [target];
for (const t of targets) {
  if (!BROWSERS.includes(t)) {
    console.error(`unknown browser "${t}" (want ${BROWSERS.join(', ')} or all)`);
    process.exit(1);
  }
  build(t, dev);
}
